// Keep generated bytes available for a visible retry; browser save completion is not observable.
import { createElement } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { downloadContent } from "@/data/downloads";

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const request = () => {
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    try {
      link.click();
    } finally {
      link.remove();
    }
  };
  const release = () => URL.revokeObjectURL(url);
  toast.message(downloadContent.ready(filename), {
    description: downloadContent.description,
    duration: Infinity,
    closeButton: true,
    // A native link preserves browser download semantics and leaves the notice open.
    action: createElement(Button, { asChild: true, size: "sm" },
      createElement("a", { href: url, download: filename }, downloadContent.action)),
    onDismiss: release,
    onAutoClose: release,
  });
  request();
}
